apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: init
  namespace: $argo_namespace
spec:
  destination:
    namespace: $argo_namespace
    server: https://kubernetes.default.svc
  project: default
  source:
    path: apps
    repoURL:  https://github.com/johnmckenna/platform-showcase.git
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true