apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cilium-gw
  namespace: kube-system
  annotations:
    # Tells cert-manager to automatically create the wildcard TLS secret using our CA
    cert-manager.io/cluster-issuer: "local-ca-issuer"
spec:
  gatewayClassName: cilium
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      hostname: "*.10.89.0.10.sslip.io"
    - name: https
      protocol: HTTPS
      port: 443
      hostname: "*.10.89.0.10.sslip.io"
      tls:
        mode: Terminate
        certificateRefs:
          - group: ""
            kind: Secret
            name: cilium-wildcard-tls-secret
      allowedRoutes:
        namespaces:
          from: All
