apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: argocd-server-tls
  namespace: $argo_namespace
spec:
  parentRefs:
    - name: argocd-gw
      namespace: argocd
  rules:
    - backendRefs:
        - name: argocd-server
          port: 443
